### ISSUE TITLE
[Suggestion] Option to output framework bundles

### ISSUE THREAD

**Issue by Danappelxx** [Conche/Conche#20]
I know you don't want to have any ties with Xcode (and that's very understandable), but frameworks are built into Swift itself (`swiftc -F <framework path>`), so it would make sense to support them.

Building a framework does *not* require the use of `xcodebuild` (though you probably know this already). For reference, here's what a Swift framework generally looks like:
```
<framework>.framework
├── Headers -> Versions/Current/Headers
├── Modules -> Versions/Current/Modules
├── Resources -> Versions/Current/Resources
├── <framework> -> Versions/Current/<framework>
└── Versions
    ├── A
    │   ├── Headers
    │   │   ├── <framework>-Swift.h
    │   │   └── <framework>.h
    │   ├── Modules
    │   │   ├── <framework>.swiftmodule
    │   │   │   ├── x86_64.swiftdoc
    │   │   │   └── x86_64.swiftmodule
    │   │   └── module.modulemap
    │   ├── Resources
    │   │   └── Info.plist
    │   └── <framework>
    └── Current -> A
```

The implementation of this turns out to be surprisingly trivial. `swiftc` already has build flags to output `.swiftdoc` & `.swiftmodule` (`-emit-module`), framework headers (`-emit-objc-header`), and the framework executable itself (`-emit-library` without the `.dylib` extension).

Anyway, I think Conche is great but its difficult to use it when it (in my understanding) only outputs executables. Allowing it to output frameworks would make it usable in not only projects that currently use Carthage/Cocoapods-rome, but also iOS, Mac, WatchOS, and TVOS applications!

Let me know if you think it's worth trying :)

**Comment by kylef** [comment]
> Anyway, I think Conche is great but its difficult to use it when it (in my understanding) only outputs executables.

It outputs both Swift modules and libraries. But the main idea is that you won't be using them outside of Conche. This is merely an implementation detail users do not need to worry about. Ideally in the future you would be able to build a variety of applications directly from Conche. Currently only command line tools and tests are supported but I'd like to see the following:

- Linux QT Application
- Linux X11 Application, etc
- Windows GUI Application
- OS X GUI Application
- iOS Application
- watchOS Application
- tvOS Application

---

I have intentions of writing either a plugin or built-in support for building and exporting frameworks to use directly with Xcode or to provide binary distribution on GitHub releases.

I don't think it makes sense to become the default format because it will be OS X specific. Conche is designed to work on other platforms like Linux and Windows once Swift becomes open-source. Which is the main reason I've not been staying away from tying this to Xcode in any way. Since Xcode itself won't be available on other platforms.

**Comment by Danappelxx** [comment]
Well, for me I don't always use Xcode but I still use the `-F` option to use frameworks (this allows me to use Cocoapods-Rome and Carthage interchangeably). Personally I came upon this specific issue with Conche when I wanted to use Stencil but I had issues with Cocoapods. It makes sense that you would want to target as many platforms & applications as possible, so I don't think you should have framework building built-in.

Anyway, I think writing a plugin for this would suit my needs. I'm willing to do it - what's the plugin system for Conche look like (does it exist yet)? Thanks for getting back to me.

**Comment by kylef** [comment]
The plugin system is currently undefined. The only thing that Conche supports for plugins is adding subcommands. You simply add a subcommand to your PATH similar to how `git` works. So, `conche foo` sub-command will look up `conchs-foo` in PATH. I have been working on a `conche-brew` plugin which allows you to easily create Homebrew formula to install your project as the first plugin/example plugin.

Let me have a think about how to design how the framework support will work and get back to you. It was one of the things I was going to tackle next.

As for using conche libraries, you can use the -I and -L flag to add import search path and library search path to build things against libraries and modules. The [Conche Makefile](https://github.com/Conche/Conche/blob/master/Makefile) is a good example of this, it includes commands to build Conche with it's dependencies in the same way Conche would build these (since we can't use Conche to build Conche).

Example:

```shell
$ swiftc -I .conche/modules -L .conche/lib
```

I'd love to talk to you about some of your projects, do you happen to be in the iOS Folks/iOS Developers Slack or on IRC?

**Comment by Danappelxx** [comment]
Sure - take your time. I'm on the [swift-lang](http://swift-lang.schwa.io) slack - feel free to pm me!

**Comment by kylef** [comment]
Closing out this issue as Conche is deprecated for the Swift Package Manager (SPM). Instead you can use SPM (https://github.com/Conche/Conche/commit/78708a9556b00d602de4c3e518a7f201b55a519b).
